### ISSUE TITLE
Display links as footnotes

### ISSUE THREAD

**Issue by groovytron** [73VW/TechnicalReport#4]
See [that comment](https://github.com/73VW/TechnicalReport/commit/167e2f0d7a9257ecf758d024699475d42daa31a4#commitcomment-27051328) for more details.

**Comment by 73VW** [comment]
@groovytron well, when I use the footnote syntax in _RST_ I can get footnotes displaying correctly (see picture below).

Could you upload a picture or an example of what you expected vs what you got? This would help to try to find a way. 

Cheers!

![image](https://user-images.githubusercontent.com/24651698/35352777-51a2b594-0145-11e8-9ab1-13b77dfb7e2b.png)
